#!/usr/bin/env bash
set -euo pipefail

# Ralph Loop Script — Autonomous CLI execution for Writ specs.
# Generated by /ralph plan. Thin wrapper: intelligence lives in PROMPT_build.md and state files.
#
# Usage:
#   ./ralph.sh              # Build mode, unlimited iterations
#   ./ralph.sh build        # Build mode (explicit)
#   ./ralph.sh build 20     # Build mode, max 20 iterations
#   ./ralph.sh plan         # Plan mode (validate artifacts only)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STATE_DIR="$PROJECT_ROOT/.writ/state"
CONFIG_FILE="$PROJECT_ROOT/.writ/config.md"

# --- Defaults (overridden by .writ/config.md Ralph keys) ---
RALPH_MAX_ITERATIONS=0
RALPH_CLI_AGENT="claude"
RALPH_CLI_MODEL="opus"
RALPH_CLI_FLAGS="--dangerously-skip-permissions --verbose"
RALPH_STOP_ON_FAILURE="false"

# --- Parse config ---
parse_config_key() {
    local key="$1"
    local default="$2"
    if [[ -f "$CONFIG_FILE" ]]; then
        local value
        value=$(grep -i "^\- \*\*${key}:\*\*" "$CONFIG_FILE" 2>/dev/null | sed 's/.*\*\*.*:\*\* *//' | head -1)
        if [[ -n "$value" ]]; then
            echo "$value"
            return
        fi
    fi
    echo "$default"
}

load_config() {
    RALPH_MAX_ITERATIONS=$(parse_config_key "Ralph Max Iterations" "$RALPH_MAX_ITERATIONS")
    RALPH_CLI_AGENT=$(parse_config_key "Ralph CLI Agent" "$RALPH_CLI_AGENT")
    RALPH_CLI_MODEL=$(parse_config_key "Ralph CLI Model" "$RALPH_CLI_MODEL")
    RALPH_CLI_FLAGS=$(parse_config_key "Ralph CLI Flags" "$RALPH_CLI_FLAGS")
    RALPH_STOP_ON_FAILURE=$(parse_config_key "Ralph Stop on Failure" "$RALPH_STOP_ON_FAILURE")
}

# --- Find latest Ralph state file ---
find_state_file() {
    local latest
    latest=$(ls -t "$STATE_DIR"/ralph-*.json 2>/dev/null | head -1)
    if [[ -z "$latest" ]]; then
        echo ""
        return
    fi
    echo "$latest"
}

# --- Read a JSON field (lightweight, no jq dependency assumed) ---
read_json_field() {
    local file="$1"
    local field="$2"
    grep -o "\"${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$file" 2>/dev/null | head -1 | sed 's/.*: *"//' | sed 's/"//'
}

# --- Check stop conditions from state ---
should_stop() {
    local state_file="$1"
    local stop_reason
    stop_reason=$(read_json_field "$state_file" "stopReason")

    if [[ -n "$stop_reason" && "$stop_reason" != "null" ]]; then
        echo "$stop_reason"
        return 0
    fi
    return 1
}

# --- Dirty tree check ---
check_clean_tree() {
    if [[ -n "$(git -C "$PROJECT_ROOT" status --porcelain 2>/dev/null)" ]]; then
        echo "❌ Working tree is dirty. Commit or stash changes before running Ralph."
        echo "   git stash  OR  git add -A && git commit -m 'WIP'"
        exit 1
    fi
}

# --- Main ---
main() {
    local mode="${1:-build}"
    local max_iterations_arg="${2:-}"

    cd "$PROJECT_ROOT"
    load_config

    # Override max iterations from argument
    if [[ -n "$max_iterations_arg" ]]; then
        RALPH_MAX_ITERATIONS="$max_iterations_arg"
    fi

    echo "⚡ Ralph Loop — Writ Autonomous Execution"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "   Mode: $mode"
    echo "   Agent: $RALPH_CLI_AGENT (model: $RALPH_CLI_MODEL)"
    if [[ "$RALPH_MAX_ITERATIONS" == "0" ]]; then
        echo "   Max iterations: unlimited"
    else
        echo "   Max iterations: $RALPH_MAX_ITERATIONS"
    fi
    echo "   Stop on failure: $RALPH_STOP_ON_FAILURE"
    echo ""

    if [[ "$mode" == "plan" ]]; then
        echo "📋 Plan mode — validating artifacts..."
        local state_file
        state_file=$(find_state_file)
        if [[ -z "$state_file" ]]; then
            echo "❌ No Ralph state file found. Run /ralph plan in Cursor first."
            exit 1
        fi
        echo "   State file: $state_file"
        echo "   Phase: $(read_json_field "$state_file" "phase")"

        if [[ ! -f "$SCRIPT_DIR/PROMPT_build.md" ]]; then
            echo "❌ PROMPT_build.md not found in scripts/"
            exit 1
        fi
        echo "   PROMPT: scripts/PROMPT_build.md ✅"
        echo ""
        echo "✅ Artifacts valid. Ready to run: ./ralph.sh build"
        exit 0
    fi

    # Build mode
    check_clean_tree

    local state_file
    state_file=$(find_state_file)
    if [[ -z "$state_file" ]]; then
        echo "❌ No Ralph state file found. Run /ralph plan in Cursor first."
        exit 1
    fi

    if [[ ! -f "$SCRIPT_DIR/PROMPT_build.md" ]]; then
        echo "❌ PROMPT_build.md not found. Run /ralph plan in Cursor first."
        exit 1
    fi

    local prompt_file="$SCRIPT_DIR/PROMPT_build.md"
    local iteration=0

    echo "📍 State: $state_file"
    echo "📄 PROMPT: $prompt_file"
    echo ""

    while true; do
        iteration=$((iteration + 1))

        # Check max iterations
        if [[ "$RALPH_MAX_ITERATIONS" != "0" && "$iteration" -gt "$RALPH_MAX_ITERATIONS" ]]; then
            echo ""
            echo "⏹️  Max iterations reached ($RALPH_MAX_ITERATIONS). Stopping."
            break
        fi

        # Check stop conditions from state
        if stop_reason=$(should_stop "$state_file"); then
            echo ""
            echo "⏹️  Stop condition met: $stop_reason"
            break
        fi

        # Display iteration header
        if [[ "$RALPH_MAX_ITERATIONS" == "0" ]]; then
            echo "━━━ Ralph iteration $iteration / ∞ ━━━"
        else
            echo "━━━ Ralph iteration $iteration / $RALPH_MAX_ITERATIONS ━━━"
        fi

        # Invoke CLI agent
        local prompt_content
        prompt_content=$(cat "$prompt_file")

        $RALPH_CLI_AGENT -p "$prompt_content" \
            --model "$RALPH_CLI_MODEL" \
            $RALPH_CLI_FLAGS \
            || true  # Don't exit on agent failure — handle via state

        # Git push after iteration (if there are new commits)
        local current_sha
        current_sha=$(git rev-parse HEAD 2>/dev/null)
        if git push 2>/dev/null; then
            echo "   ✅ Pushed to remote"
        else
            echo "   ⚠️  Push failed (remote unreachable?) — commit preserved locally"
        fi

        # Re-read state file (agent may have updated it)
        state_file=$(find_state_file)

        # Check stop-on-failure
        if [[ "$RALPH_STOP_ON_FAILURE" == "true" ]]; then
            local phase
            phase=$(read_json_field "$state_file" "phase")
            # Check if the last iteration failed by reading the most recent iteration result
            local last_result
            last_result=$(grep -o '"result"[[:space:]]*:[[:space:]]*"[^"]*"' "$state_file" 2>/dev/null | tail -1 | sed 's/.*: *"//' | sed 's/"//')
            if [[ "$last_result" == "failed" || "$last_result" == "environment-error" ]]; then
                echo ""
                echo "⏹️  Stop on failure: last iteration result was '$last_result'"
                break
            fi
        fi

        echo ""
    done

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "⚡ Ralph loop finished after $iteration iteration(s)."
    echo "   Review results: /ralph status (in Cursor)"
    echo "   State file: $state_file"
}

main "$@"
